/*
 * Social Network Mock Data
 * ────────────────────────
 * Demo data for the Facebook-style social feed
 */

import type { Post, Story, Notification, FriendRequest } from "./socialTypes";
import type { User } from "./types";
import { mockUsers, mockCurrentUser } from "./mockData";

const SAMPLE_POST_IMG = "https://d2xsxph8kpxj0f.cloudfront.net/310519663435216308/2fgaxJv4JtYGP66iKhZqNw/nexus-sample-post-7vw4dpatFB9ceteUmDoM65.webp";

export const mockPosts: Post[] = [
  {
    id: "post-1",
    user_id: "user-2",
    content: "Just finished the new dashboard redesign! Really happy with how the data visualization turned out. What do you all think? 🎨✨",
    media: [
      {
        id: "media-1",
        url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800",
        type: "image",
      },
    ],
    privacy: "public",
    likes_count: 24,
    comments_count: 8,
    shares_count: 3,
    is_liked: false,
    is_shared: false,
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString(),
    user: mockUsers[1],
    comments: [
      {
        id: "comment-1",
        post_id: "post-1",
        user_id: "user-3",
        content: "This looks amazing! Love the color scheme 🔥",
        likes_count: 5,
        is_liked: false,
        created_at: new Date(Date.now() - 3000000).toISOString(),
        user: mockUsers[2],
      },
      {
        id: "comment-2",
        post_id: "post-1",
        user_id: "user-4",
        content: "Great work Alice! The charts are so clean.",
        likes_count: 2,
        is_liked: true,
        created_at: new Date(Date.now() - 2400000).toISOString(),
        user: mockUsers[3],
      },
    ],
  },
  {
    id: "post-2",
    user_id: "user-3",
    content: "Beautiful sunset from my evening hike today. Nature never disappoints! 🌅🏔️ Sometimes you just need to disconnect and recharge.",
    media: [
      {
        id: "media-2",
        url: SAMPLE_POST_IMG,
        type: "image",
      },
    ],
    privacy: "public",
    likes_count: 47,
    comments_count: 12,
    shares_count: 7,
    is_liked: true,
    is_shared: false,
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: new Date(Date.now() - 7200000).toISOString(),
    user: mockUsers[2],
    comments: [
      {
        id: "comment-3",
        post_id: "post-2",
        user_id: "user-5",
        content: "Wow, that's breathtaking! Where is this?",
        likes_count: 3,
        is_liked: false,
        created_at: new Date(Date.now() - 6000000).toISOString(),
        user: mockUsers[4],
      },
    ],
  },
  {
    id: "post-3",
    user_id: "user-4",
    content: "Excited to announce that our team just shipped v2.0! 🚀 After months of hard work, we've completely rebuilt the platform from the ground up. New features include:\n\n• Real-time collaboration\n• AI-powered suggestions\n• Dark mode (finally!)\n• 50% faster load times\n\nCheck it out and let me know what you think!",
    media: [],
    privacy: "public",
    likes_count: 89,
    comments_count: 23,
    shares_count: 15,
    is_liked: false,
    is_shared: false,
    created_at: new Date(Date.now() - 14400000).toISOString(),
    updated_at: new Date(Date.now() - 14400000).toISOString(),
    user: mockUsers[3],
    comments: [],
  },
  {
    id: "post-4",
    user_id: "user-5",
    content: "Coffee and code — my favorite morning combo ☕💻 Working on some exciting new features today!",
    media: [
      {
        id: "media-3",
        url: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=800",
        type: "image",
      },
    ],
    privacy: "friends",
    likes_count: 18,
    comments_count: 4,
    shares_count: 1,
    is_liked: false,
    is_shared: false,
    created_at: new Date(Date.now() - 28800000).toISOString(),
    updated_at: new Date(Date.now() - 28800000).toISOString(),
    user: mockUsers[4],
    comments: [],
  },
  {
    id: "post-5",
    user_id: "user-6",
    content: "Just completed the AWS Solutions Architect certification! 🎉 It was a tough journey but totally worth it. Happy to share study tips with anyone interested.",
    media: [],
    privacy: "public",
    likes_count: 156,
    comments_count: 34,
    shares_count: 22,
    is_liked: true,
    is_shared: false,
    created_at: new Date(Date.now() - 43200000).toISOString(),
    updated_at: new Date(Date.now() - 43200000).toISOString(),
    user: mockUsers[5],
    comments: [
      {
        id: "comment-4",
        post_id: "post-5",
        user_id: "user-2",
        content: "Congratulations! 🎊 Would love to hear your study strategy.",
        likes_count: 8,
        is_liked: false,
        created_at: new Date(Date.now() - 40000000).toISOString(),
        user: mockUsers[1],
      },
    ],
  },
  {
    id: "post-6",
    user_id: "user-2",
    content: "Team lunch at the new Italian place downtown! Great food, even better company. 🍝🍷",
    media: [
      {
        id: "media-4",
        url: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800",
        type: "image",
      },
      {
        id: "media-5",
        url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800",
        type: "image",
      },
    ],
    privacy: "friends",
    likes_count: 32,
    comments_count: 9,
    shares_count: 2,
    is_liked: false,
    is_shared: false,
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
    user: mockUsers[1],
    comments: [],
  },
];

export const mockStories: Story[] = [
  {
    id: "story-1",
    user_id: "user-1",
    media_url: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=400",
    media_type: "image",
    caption: "Working late tonight",
    views_count: 0,
    created_at: new Date(Date.now() - 3600000).toISOString(),
    expires_at: new Date(Date.now() + 82800000).toISOString(),
    user: mockCurrentUser,
  },
  {
    id: "story-2",
    user_id: "user-2",
    media_url: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=400",
    media_type: "image",
    caption: "Team meeting vibes",
    views_count: 15,
    created_at: new Date(Date.now() - 7200000).toISOString(),
    expires_at: new Date(Date.now() + 79200000).toISOString(),
    user: mockUsers[1],
  },
  {
    id: "story-3",
    user_id: "user-3",
    media_url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400",
    media_type: "image",
    caption: "Mountain views 🏔️",
    views_count: 28,
    created_at: new Date(Date.now() - 14400000).toISOString(),
    expires_at: new Date(Date.now() + 72000000).toISOString(),
    user: mockUsers[2],
  },
  {
    id: "story-4",
    user_id: "user-4",
    media_url: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400",
    media_type: "image",
    caption: "Coding session",
    views_count: 12,
    created_at: new Date(Date.now() - 21600000).toISOString(),
    expires_at: new Date(Date.now() + 64800000).toISOString(),
    user: mockUsers[3],
  },
  {
    id: "story-5",
    user_id: "user-5",
    media_url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400",
    media_type: "image",
    caption: "New setup! 💻",
    views_count: 20,
    created_at: new Date(Date.now() - 28800000).toISOString(),
    expires_at: new Date(Date.now() + 57600000).toISOString(),
    user: mockUsers[4],
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "notif-1",
    user_id: "user-1",
    type: "like",
    content: "liked your post",
    is_read: false,
    reference_id: "post-1",
    created_at: new Date(Date.now() - 1800000).toISOString(),
    actor: mockUsers[1],
  },
  {
    id: "notif-2",
    user_id: "user-1",
    type: "comment",
    content: "commented on your post",
    is_read: false,
    reference_id: "post-1",
    created_at: new Date(Date.now() - 3600000).toISOString(),
    actor: mockUsers[2],
  },
  {
    id: "notif-3",
    user_id: "user-1",
    type: "friend_request",
    content: "sent you a friend request",
    is_read: true,
    created_at: new Date(Date.now() - 7200000).toISOString(),
    actor: mockUsers[3],
  },
  {
    id: "notif-4",
    user_id: "user-1",
    type: "share",
    content: "shared your post",
    is_read: true,
    reference_id: "post-2",
    created_at: new Date(Date.now() - 14400000).toISOString(),
    actor: mockUsers[4],
  },
];

export const mockFriendRequests: FriendRequest[] = [
  {
    id: "fr-1",
    from_user_id: "user-4",
    to_user_id: "user-1",
    status: "pending",
    created_at: new Date(Date.now() - 7200000).toISOString(),
    from_user: mockUsers[3],
  },
  {
    id: "fr-2",
    from_user_id: "user-6",
    to_user_id: "user-1",
    status: "pending",
    created_at: new Date(Date.now() - 14400000).toISOString(),
    from_user: mockUsers[5],
  },
];

export const mockSuggestedFriends: User[] = [
  {
    id: "user-7",
    email: "grace@nexuschat.app",
    username: "grace_ai",
    display_name: "Grace Kim",
    status: "online",
    status_text: "ML Engineer",
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "user-8",
    email: "henry@nexuschat.app",
    username: "henry_data",
    display_name: "Henry Park",
    status: "offline",
    status_text: "Data Scientist",
    created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: "user-9",
    email: "iris@nexuschat.app",
    username: "iris_ux",
    display_name: "Iris Thompson",
    status: "online",
    status_text: "UX Researcher",
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
];
